src/main/java/ai/asserts/aws/MetricNameUtil.java, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigProvider.java, src/main/java/ai/asserts/aws/cloudwatch/model/CWNamespace.java, src/main/java/ai/asserts/aws/cloudwatch/query/MetricQueryProvider.java, src/main/java/ai/asserts/aws/resource/TagFilterResourceProvider.java, src/test/java/ai/asserts/aws/MetricNameUtilTest.java, src/test/java/ai/asserts/aws/cloudwatch/query/MetricQueryProviderTest.java, src/test/java/ai/asserts/aws/resource/TagFilterResourceProviderTest.java
=> Support custom namespace

README.md, src/dist/README.md, src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/cloudwatch/query/MetricQueryProvider.java, src/main/java/ai/asserts/aws/resource/TagFilterResourceProvider.java, src/test/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigProviderTest.java
=> Fix regression in Namespace name handling

src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/lambda/LambdaFunctionScraper.java, src/test/java/ai/asserts/aws/exporter/LambdaEventSourceExporterTest.java, src/test/java/ai/asserts/aws/lambda/LambdaFunctionScraperTest.java
=> Fix lambda namespace bug

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/cloudwatch/config/MetricConfig.java, src/main/java/ai/asserts/aws/cloudwatch/model/CWNamespace.java, src/main/java/ai/asserts/aws/exporter/LabelBuilder.java, src/main/java/ai/asserts/aws/exporter/ResourceTagExporter.java, src/main/java/ai/asserts/aws/resource/Resource.java, src/main/java/ai/asserts/aws/resource/ResourceMapper.java, src/test/java/ai/asserts/aws/cloudwatch/config/MetricConfigTest.java, src/test/java/ai/asserts/aws/exporter/LabelBuilderTest.java, src/test/java/ai/asserts/aws/exporter/ResourceTagExporterTest.java, src/test/java/ai/asserts/aws/resource/ResourceMapperTest.java, src/test/java/ai/asserts/aws/resource/ResourceTest.java
=> Dimension filter changes

src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/exporter/LabelBuilder.java, src/test/java/ai/asserts/aws/exporter/LabelBuilderTest.java
=> Add namespace in ecs scrape target label

src/main/java/ai/asserts/aws/CallRateLimiter.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/MetricTaskManager.java, src/main/java/ai/asserts/aws/TaskThreadPool.java, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/cloudwatch/query/MetricQueryProvider.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/exporter/LambdaCapacityExporter.java, src/main/java/ai/asserts/aws/exporter/LambdaEventSourceExporter.java, src/main/java/ai/asserts/aws/exporter/LambdaInvokeConfigExporter.java, src/main/java/ai/asserts/aws/exporter/MetricScrapeTask.java, src/main/java/ai/asserts/aws/lambda/LambdaFunctionScraper.java, src/main/java/ai/asserts/aws/lambda/LogEventScraper.java, src/main/java/ai/asserts/aws/resource/TagFilterResourceProvider.java, src/test/java/ai/asserts/aws/CallRateLimiterTest.java, src/test/java/ai/asserts/aws/TaskThreadPoolTest.java, src/test/java/ai/asserts/aws/cloudwatch/query/MetricQueryProviderTest.java, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java, src/test/java/ai/asserts/aws/exporter/LambdaCapacityExporterTest.java, src/test/java/ai/asserts/aws/exporter/LambdaEventSourceExporterTest.java, src/test/java/ai/asserts/aws/exporter/LambdaInvokeConfigExporterTest.java, src/test/java/ai/asserts/aws/exporter/MetricScrapeTaskTest.java, src/test/java/ai/asserts/aws/lambda/LambdaFunctionScraperTest.java, src/test/java/ai/asserts/aws/lambda/LogEventScraperTest.java, src/test/java/ai/asserts/aws/resource/TagFilterResourceProviderTest.java
[ch8994]
Rate limit AWS API Calls
=> Aws throttling issue

src/main/java/ai/asserts/aws/CallRateLimiter.java, src/test/java/ai/asserts/aws/CallRateLimiterTest.java
=> Fix throttling logic

src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/MetricTaskManager.java, src/main/java/ai/asserts/aws/RateLimiter.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/MetricTaskManagerTest.java
=> Throttle log scrape

src/main/java/ai/asserts/aws/RateLimiter.java
=> Throttle Log call further

src/main/java/ai/asserts/aws/RateLimiter.java, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/exporter/LambdaLogMetricScrapeTask.java, src/main/resources/logback.xml, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java, src/test/java/ai/asserts/aws/exporter/LambdaLogMetricScrapeTaskTest.java
=> Throttling experiment v2

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigProvider.java, src/main/java/ai/asserts/aws/exporter/ScrapeConfigExporter.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigProviderTest.java, src/test/java/ai/asserts/aws/exporter/ScrapeConfigExporterTest.java, src/test/resources/cloudwatch_scrape_config.yml
=> Increase scrape interval to keep costs under control

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/exporter/LambdaCapacityExporter.java, src/test/java/ai/asserts/aws/exporter/LambdaCapacityExporterTest.java
=> Remove unused metrics

src/main/java/ai/asserts/aws/exporter/LabelBuilder.java, src/test/java/ai/asserts/aws/exporter/LabelBuilderTest.java
=> Rename label `namespace` to `cw_namespace`

src/main/java/ai/asserts/aws/exporter/LambdaCapacityExporter.java, src/test/java/ai/asserts/aws/exporter/LambdaCapacityExporterTest.java
=> Use Config to get Lambda Memory Limit

src/main/java/ai/asserts/aws/exporter/LambdaCapacityExporter.java, src/test/java/ai/asserts/aws/exporter/LambdaCapacityExporterTest.java
[ch9993]
This reverts commit 30eb28bc
=> Revert "Use Config to get Lambda Memory Limit"

src/main/java/ai/asserts/aws/cloudwatch/TimeWindowBuilder.java, src/main/java/ai/asserts/aws/exporter/MetricScrapeTask.java, src/main/java/ai/asserts/aws/lambda/LogEventScraper.java, src/test/java/ai/asserts/aws/cloudwatch/TimeWindowBuilderTest.java, src/test/java/ai/asserts/aws/exporter/MetricScrapeTaskTest.java, src/test/java/ai/asserts/aws/lambda/LogEventScraperTest.java
=> Fix metric statistic period

src/main/java/ai/asserts/aws/cloudwatch/config/MetricConfig.java
=> Fix dimension filter

AWSCloudFormationTemplate.json
=> Add CF Template to create IAM Policy, Role and Instance profile

src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java
=> ECS sd target labels region and namespace

src/main/java/ai/asserts/aws/exporter/LambdaCapacityExporter.java, src/test/java/ai/asserts/aws/exporter/LambdaCapacityExporterTest.java
=> Add namespace to metadata metric

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/test/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigTest.java, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
=> Separate flag for ECS Service Discovery

README.md, src/dist/README.md
Group content into expandable sections
=> Make README.md concise

src/main/java/ai/asserts/aws/exporter/ResourceTagExporter.java, src/main/java/ai/asserts/aws/exporter/ScrapeConfigExporter.java, src/test/java/ai/asserts/aws/exporter/ResourceTagExporterTest.java
=> Fix no data scenario when building metric sample family

src/dist/conf/cloudwatch_scrape_config_sample.yml
=> Switch back to using the `used_memory_max`

src/dist/conf/cloudwatch_scrape_config_sample.yml
=> Add `memory_utilization` for comparison with `used_memory_max`

src/main/java/ai/asserts/aws/exporter/LambdaCapacityExporter.java, src/test/java/ai/asserts/aws/exporter/LambdaCapacityExporterTest.java
=> Export function reserved concurrency

src/dist/conf/cloudwatch_scrape_config_sample.yml
=> Enable log scraping for Tetra demo

src/main/java/ai/asserts/aws/RateLimiter.java, src/main/java/ai/asserts/aws/cloudwatch/query/MetricQueryProvider.java, src/main/java/ai/asserts/aws/exporter/BasicMetricCollector.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java, src/main/java/ai/asserts/aws/exporter/LambdaCapacityExporter.java, src/main/java/ai/asserts/aws/exporter/LambdaEventSourceExporter.java, src/main/java/ai/asserts/aws/exporter/LambdaInvokeConfigExporter.java, src/main/java/ai/asserts/aws/exporter/MetricScrapeTask.java, src/main/java/ai/asserts/aws/lambda/LambdaFunctionScraper.java, src/main/java/ai/asserts/aws/lambda/LogEventScraper.java, src/main/java/ai/asserts/aws/resource/TagFilterResourceProvider.java, src/test/java/ai/asserts/aws/RateLimiterTest.java, src/test/java/ai/asserts/aws/cloudwatch/query/MetricQueryProviderTest.java, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java, src/test/java/ai/asserts/aws/exporter/ECSTaskUtilTest.java, src/test/java/ai/asserts/aws/exporter/LambdaCapacityExporterTest.java, src/test/java/ai/asserts/aws/exporter/LambdaEventSourceExporterTest.java, src/test/java/ai/asserts/aws/exporter/LambdaInvokeConfigExporterTest.java, src/test/java/ai/asserts/aws/exporter/MetricScrapeTaskTest.java, src/test/java/ai/asserts/aws/lambda/LambdaFunctionScraperTest.java, src/test/java/ai/asserts/aws/lambda/LogEventScraperTest.java, src/test/java/ai/asserts/aws/resource/TagFilterResourceProviderTest.java
=> Improve internal metric captures

build.gradle, gradle.properties, src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/MetricTaskManager.java, src/main/java/ai/asserts/aws/RateLimiter.java, src/main/java/ai/asserts/aws/cloudwatch/config/NamespaceConfig.java, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/exporter/ResourceExporter.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/exporter/ResourceExporterTest.java
=> Discover AWS Resources using config API

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/exporter/ResourceExporter.java, src/test/java/ai/asserts/aws/exporter/ResourceExporterTest.java
=> Discover more resource types

src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmController.java, src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmResponse.java
Support for PUT method
[ch10882]
=> adding put support

build.gradle, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/RateLimiter.java, src/main/java/ai/asserts/aws/cloudwatch/config/NamespaceConfig.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java, src/main/java/ai/asserts/aws/exporter/LBToECSRoutingBuilder.java, src/main/java/ai/asserts/aws/exporter/ResourceExporter.java, src/main/java/ai/asserts/aws/exporter/ResourceRelationExporter.java, src/main/java/ai/asserts/aws/exporter/TargetGroupLBMapProvider.java, src/main/java/ai/asserts/aws/resource/ResourceMapper.java, src/main/java/ai/asserts/aws/resource/ResourceRelation.java, src/main/java/ai/asserts/aws/resource/ResourceType.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java, src/test/java/ai/asserts/aws/exporter/LBToECSRoutingBuilderTest.java, src/test/java/ai/asserts/aws/exporter/ResourceRelationExporterTest.java, src/test/java/ai/asserts/aws/exporter/TargetGroupLBMapProviderTest.java, src/test/java/ai/asserts/aws/resource/ResourceMapperTest.java
=> Lb ecs route builder

src/dist/conf/cloudwatch_scrape_config_sample.yml
=> Specify the container that needs to be scraped in AWS Exporter ECS Task

build.gradle, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/exporter/LBToASGRelationBuilder.java, src/main/java/ai/asserts/aws/exporter/ResourceRelationExporter.java, src/main/java/ai/asserts/aws/resource/Resource.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/exporter/LBToASGRelationBuilderTest.java, src/test/java/ai/asserts/aws/exporter/ResourceRelationExporterTest.java, src/test/java/ai/asserts/aws/resource/ResourceTest.java
=> Emit LB to ASG Relationship

src/main/java/ai/asserts/aws/exporter/LBToASGRelationBuilder.java, src/test/java/ai/asserts/aws/exporter/LBToASGRelationBuilderTest.java
=> Use rate limiter and add logging

src/main/java/ai/asserts/aws/exporter/ResourceExporter.java, src/main/java/ai/asserts/aws/lambda/LogEventScraper.java, src/main/java/ai/asserts/aws/resource/ResourceMapper.java, src/main/java/ai/asserts/aws/resource/ResourceType.java, src/test/java/ai/asserts/aws/resource/ResourceMapperTest.java
[ch10931]
Additional Resource Type Mapping
Logging improvement
=> Additional Resource Type Mapping

src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmController.java
Adding try catch to log the exception for debugging.
[ch10882]
=> adding try catch for controller

src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmController.java
Logging the Exception, though it was working in local it doesn't log the exception in container so logging specifically to find out the issue.
[ch10882]
=> log exception

src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmController.java, src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmRecord.java, src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmRequest.java, src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmControllerTest.java
Mapping request object to match the format Kinesis push stream is sending.
[ch10882]
=> alarm request object mapping

src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmMetricExporterTest.java
=> Fix IDE compiler errors

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/cloudwatch/config/LogScrapeConfig.java, src/test/java/ai/asserts/aws/cloudwatch/config/LogScrapeConfigTest.java
=> Function names list

src/main/java/ai/asserts/aws/BeanConfiguration.java, src/main/java/ai/asserts/aws/cloudwatch/metrics/MetricResponse.java, src/main/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamController.java, src/main/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamProcessor.java, src/main/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamServlet.java, src/test/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamProcessorTest.java, src/test/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamServletTest.java
=> Metric Stream callback

src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmMetricExporter.java, src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmMetricExporterTest.java
Setting timestamp is not showing the metric, setting to default value.
[ch10882]
=> setting metric timestamp to default

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/MetricNameUtil.java, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/cloudwatch/config/TagExportConfig.java, src/main/java/ai/asserts/aws/cloudwatch/query/MetricQueryProvider.java, src/main/java/ai/asserts/aws/exporter/LBToASGRelationBuilder.java, src/main/java/ai/asserts/aws/exporter/LabelBuilder.java, src/main/java/ai/asserts/aws/exporter/LambdaCapacityExporter.java, src/main/java/ai/asserts/aws/exporter/LambdaEventSourceExporter.java, src/main/java/ai/asserts/aws/exporter/LambdaInvokeConfigExporter.java, src/main/java/ai/asserts/aws/exporter/ResourceExporter.java, src/main/java/ai/asserts/aws/exporter/TargetGroupLBMapProvider.java, src/main/java/ai/asserts/aws/lambda/LambdaFunctionScraper.java, src/main/java/ai/asserts/aws/lambda/LogEventMetricEmitter.java, src/main/java/ai/asserts/aws/resource/Resource.java, src/main/java/ai/asserts/aws/resource/ResourceTagHelper.java, src/test/java/ai/asserts/aws/MetricNameUtilTest.java, src/test/java/ai/asserts/aws/cloudwatch/config/ECSTaskDefScrapeConfigTest.java, src/test/java/ai/asserts/aws/cloudwatch/config/TagExportConfigTest.java, src/test/java/ai/asserts/aws/cloudwatch/query/MetricQueryProviderTest.java, src/test/java/ai/asserts/aws/exporter/AccountIDProviderTest.java, src/test/java/ai/asserts/aws/exporter/LBToASGRelationBuilderTest.java, src/test/java/ai/asserts/aws/exporter/LambdaCapacityExporterTest.java, src/test/java/ai/asserts/aws/exporter/LambdaEventSourceExporterTest.java, src/test/java/ai/asserts/aws/exporter/LambdaInvokeConfigExporterTest.java, src/test/java/ai/asserts/aws/exporter/ResourceExporterTest.java, src/test/java/ai/asserts/aws/exporter/TargetGroupLBMapProviderTest.java, src/test/java/ai/asserts/aws/lambda/LambdaFunctionScraperTest.java, src/test/java/ai/asserts/aws/lambda/LogEventEmitterTest.java, src/test/java/ai/asserts/aws/resource/ResourceTagHelperTest.java
=> More unit tests

src/main/java/ai/asserts/aws/exporter/LBToASGRelationBuilder.java, src/main/java/ai/asserts/aws/exporter/LambdaEventSourceExporter.java, src/main/java/ai/asserts/aws/exporter/ResourceExporter.java, src/main/java/ai/asserts/aws/exporter/TargetGroupLBMapProvider.java, src/main/java/ai/asserts/aws/resource/Resource.java, src/test/java/ai/asserts/aws/exporter/LambdaEventSourceExporterTest.java
=> Fix bug in Event source exporter. Add try catch blocks

src/main/java/ai/asserts/aws/exporter/LBToLambdaRoutingBuilder.java, src/main/java/ai/asserts/aws/exporter/ResourceRelationExporter.java, src/main/java/ai/asserts/aws/resource/ResourceMapper.java, src/main/java/ai/asserts/aws/resource/ResourceType.java, src/test/java/ai/asserts/aws/exporter/LBToLambdaRoutingBuilderTest.java, src/test/java/ai/asserts/aws/exporter/ResourceRelationExporterTest.java, src/test/java/ai/asserts/aws/resource/ResourceMapperTest.java
=> Export LB Lambda relation

src/main/java/ai/asserts/aws/resource/ResourceMapper.java, src/main/java/ai/asserts/aws/resource/ResourceTagHelper.java, src/test/java/ai/asserts/aws/resource/ResourceMapperTest.java, src/test/java/ai/asserts/aws/resource/ResourceTagHelperTest.java
=> Exclude LB type from LB name

build.gradle, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/cloudwatch/model/CWNamespace.java, src/main/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporter.java, src/main/java/ai/asserts/aws/exporter/ResourceRelationExporter.java, src/main/java/ai/asserts/aws/resource/ResourceMapper.java, src/main/java/ai/asserts/aws/resource/ResourceType.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporterTest.java, src/test/java/ai/asserts/aws/exporter/ResourceRelationExporterTest.java
[ch11173]
Export EC2 to EBS Volume relationship
Introduce new resource types
Map resource type to the namespace in `ResourceType` enum
=> Export EC2 to EBS Volume relationship

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/cloudwatch/config/DimensionToLabel.java, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/cloudwatch/model/CWNamespace.java, src/main/java/ai/asserts/aws/resource/ResourceType.java, src/test/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigProviderTest.java, src/test/resources/cloudwatch_scrape_config.yml
=> Add cloudwatch alarm labels to entity name label mapping

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmFetcher.java, src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmMetricConverter.java, src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmMetricStat.java, src/main/java/ai/asserts/aws/cloudwatch/config/DimensionToLabel.java, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfig.java, src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmFetcherTest.java, src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmMetricConverterTest.java, src/test/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigTest.java
=> Add labels to help attach cloud watch alarm to entity

build.gradle, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/exporter/ApiGatewayToLambdaBuilder.java, src/main/java/ai/asserts/aws/exporter/ResourceRelationExporter.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/exporter/ApiGatewayToLambdaBuilderTest.java, src/test/java/ai/asserts/aws/exporter/ResourceRelationExporterTest.java
=> Export ApiGateway Lambda Invocation relation

src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/cloudwatch/config/ECSTaskDefScrapeConfig.java, src/main/java/ai/asserts/aws/cloudwatch/config/NamespaceConfig.java, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigProvider.java, src/main/java/ai/asserts/aws/cloudwatch/config/TagExportConfig.java, src/test/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigProviderTest.java, src/test/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamProcessorTest.java
=> Load Configuration from S3

src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java, src/test/java/ai/asserts/aws/exporter/ECSTaskUtilTest.java
=> Scrape metrics only from declared containers

src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigProvider.java, src/main/java/ai/asserts/aws/exporter/AccountIDProvider.java, src/test/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigProviderTest.java, src/test/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamProcessorTest.java, src/test/java/ai/asserts/aws/exporter/AccountIDProviderTest.java
=> Config load failure should not cause process to exist

src/dist/conf/cloudwatch_scrape_config_sample.yml
=> Disable fetch based Lambda invocations, errors and totals

src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigProvider.java, src/main/java/ai/asserts/aws/exporter/ApiGatewayToLambdaBuilder.java, src/main/java/ai/asserts/aws/exporter/LBToLambdaRoutingBuilder.java, src/test/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigProviderTest.java, src/test/java/ai/asserts/aws/exporter/ApiGatewayToLambdaBuilderTest.java, src/test/java/ai/asserts/aws/exporter/LBToLambdaRoutingBuilderTest.java
=> Close clients

src/main/java/ai/asserts/aws/exporter/ResourceExporter.java
=> Set `job` to `name` and if not `name` then `id`

src/main/java/ai/asserts/aws/exporter/ResourceExporter.java, src/main/java/ai/asserts/aws/resource/ResourceMapper.java
=> Fix missing ALBs

src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmFetcher.java, src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmMetricConverter.java, src/main/java/ai/asserts/aws/exporter/ResourceExporter.java, src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmFetcherTest.java
=> Set `job` from resource arn in `aws_resource` only if not set

src/main/java/ai/asserts/aws/exporter/ResourceExporter.java
=> Set `id` and `name` conditionally

build.gradle, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/exporter/KinesisAnalyticsExporter.java, src/main/java/ai/asserts/aws/exporter/KinesisFirehoseExporter.java, src/main/java/ai/asserts/aws/resource/Resource.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java
=> Export Kinesis Firehose and Analytics

src/main/java/ai/asserts/aws/exporter/ResourceExporter.java, src/main/java/ai/asserts/aws/resource/Resource.java, src/main/java/ai/asserts/aws/resource/ResourceTagHelper.java, src/test/java/ai/asserts/aws/exporter/ResourceExporterTest.java
=> Identify if ASG is for K8S

src/main/java/ai/asserts/aws/exporter/ResourceExporter.java, src/main/java/ai/asserts/aws/resource/ResourceTagHelper.java
=> Fix loadbalancernames empty list

src/main/java/ai/asserts/aws/resource/ResourceConfigController.java
basic controller to get config change events.
[ch11385]
=> resource config change support

src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmFetcher.java, src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmFetcherTest.java
Adding comparsionOperator alarm field to the metric.
[sc11404]
=> add alarm operator field in metric

src/main/java/ai/asserts/aws/exporter/KinesisAnalyticsExporter.java
Adding job label for kinesis analytics to be used to define entity.
[ch11487]
=> Adding job label for KinesisAnalytics

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/resource/ResourceMapper.java, src/main/java/ai/asserts/aws/resource/ResourceType.java, src/test/java/ai/asserts/aws/resource/ResourceMapperTest.java
Adding resource mapping and resource type for redshift
[ch11518]
=> Support for aws redshift cluster

src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmController.java, src/main/java/ai/asserts/aws/cloudwatch/alarms/FirehoseEventRequest.java, src/main/java/ai/asserts/aws/cloudwatch/alarms/RecordData.java, src/main/java/ai/asserts/aws/resource/ResourceConfigChange.java, src/main/java/ai/asserts/aws/resource/ResourceConfigChangeDetail.java, src/main/java/ai/asserts/aws/resource/ResourceConfigController.java, src/main/java/ai/asserts/aws/resource/ResourceConfigDiff.java, src/main/java/ai/asserts/aws/resource/ResourceConfigItem.java, src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmControllerTest.java
Define resource config change event structure and decrypt the message to get the strcuture.
Log the event key information
[ch11385]
=> Resource Config change event

src/dist/conf/default_relabel_rules.yml
=> Add relabel for namespace

src/main/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamController.java, src/test/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamControllerTest.java
=> Pause stream callback based metrics for now

src/main/java/ai/asserts/aws/resource/ResourceConfigController.java, src/test/java/ai/asserts/aws/resource/ResourceConfigControllerTest.java
Update change type field to camel case.
[ch11385]
=> Camel case for change type

build.gradle, src/dist/conf/default_relabel_rules.yml, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/ApiAuthenticator.java, src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmController.java, src/main/java/ai/asserts/aws/cloudwatch/config/AuthConfig.java, src/main/java/ai/asserts/aws/cloudwatch/config/RelabelConfig.java, src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamController.java, src/main/java/ai/asserts/aws/resource/ResourceConfigController.java, src/test/java/ai/asserts/aws/ApiAuthenticatorTest.java, src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmControllerTest.java, src/test/java/ai/asserts/aws/cloudwatch/config/RelabelConfigTest.java, src/test/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamControllerTest.java, src/test/java/ai/asserts/aws/resource/ResourceConfigControllerTest.java
=> Make stream callback APIs secure

src/main/java/ai/asserts/aws/resource/ResourceConfigController.java, src/test/java/ai/asserts/aws/resource/ResourceConfigControllerTest.java
Using dimension to label configuration set the entity type, we don't have dimension so go with namespace and find out the entity type.
[ch11385]
=> Set EntityType using dimensiontolabel config

src/main/java/ai/asserts/aws/cloudwatch/TimeWindowBuilder.java, src/main/java/ai/asserts/aws/resource/ResourceChangedItem.java, src/main/java/ai/asserts/aws/resource/ResourceConfigController.java, src/test/java/ai/asserts/aws/resource/ResourceConfigControllerTest.java
When properties changed information is available build alert name with details else use change type as alert name.
[ch11385]
=> Alertname with details

src/dist/conf/default_relabel_rules.yml, src/main/java/ai/asserts/aws/exporter/BasicMetricCollector.java, src/test/java/ai/asserts/aws/exporter/BasicMetricCollectorTest.java
=> Add request type

config/src/main/java/ai/asserts/aws/config/AuthConfig.java, config/src/main/java/ai/asserts/aws/config/ECSTaskDefScrapeConfig.java, config/src/main/java/ai/asserts/aws/config/MetricConfig.java, config/src/main/java/ai/asserts/aws/config/NamespaceConfig.java, config/src/test/java/ai/asserts/aws/config/MetricConfigTest.java, config/src/test/java/ai/asserts/aws/config/NamespaceConfigTest.java, src/main/java/ai/asserts/aws/MetricTaskManager.java, src/main/java/ai/asserts/aws/cloudwatch/query/MetricQueryBuilder.java, src/main/java/ai/asserts/aws/cloudwatch/query/MetricQueryProvider.java, src/main/java/ai/asserts/aws/exporter/ScrapeConfigExporter.java, src/test/java/ai/asserts/aws/ScrapeConfigProviderTest.java, src/test/java/ai/asserts/aws/cloudwatch/query/MetricQueryBuilderTest.java, src/test/java/ai/asserts/aws/cloudwatch/query/MetricQueryProviderTest.java, src/test/java/ai/asserts/aws/exporter/ScrapeConfigExporterTest.java
=> Add `@JsonIgnore` where required

config/build.gradle
=> Remove hard coded version

src/main/java/ai/asserts/aws/MetricTaskManager.java, src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmFetcher.java, src/test/java/ai/asserts/aws/MetricTaskManagerTest.java
=> Fetch CloudWatch alarms through pull model at a schedule

src/main/java/ai/asserts/aws/DownloadLogController.java
=> API to Download Log File

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/MetricTaskManager.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/MetricTaskManagerTest.java, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
[ch12326]
Emit ECS resource metrics using direct API
=> Emit ECS resource metric using direct API

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/exporter/S3BucketExporter.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/exporter/S3BucketExporterTest.java
S3 bucket resource import using the direct API instead of config API.
[ch12326]
=> S3 Bucket Resource Support

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/exporter/SQSQueueExporter.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java
=> SQS Queue resource metrics through direct API

build.gradle, src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/exporter/RedshiftExporter.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/exporter/RedshiftExporterTest.java
Redshift cluster resource discovery using direct API.
[ch12326]
=> Redshift cluster Resource Support

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/exporter/LoadBalancerExporter.java, src/main/java/ai/asserts/aws/exporter/RedshiftExporter.java, src/main/java/ai/asserts/aws/exporter/S3BucketExporter.java, src/main/java/ai/asserts/aws/exporter/SQSQueueExporter.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/exporter/RedshiftExporterTest.java, src/test/java/ai/asserts/aws/exporter/S3BucketExporterTest.java
=> LBs from direct api

build.gradle, src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/exporter/KinesisStreamExporter.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/exporter/KinesisStreamExporterTest.java
Kinesis stream discovery using direct API
[ch12326]
=> Kinesis Stream Resource Support

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporter.java, src/test/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporterTest.java
=> EC2 Instance from direct API

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/exporter/ApiGatewayToLambdaBuilder.java, src/main/java/ai/asserts/aws/resource/ResourceTagHelper.java, src/test/java/ai/asserts/aws/exporter/ApiGatewayToLambdaBuilderTest.java
=> Api gateway resource from direct api

build.gradle, src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/exporter/KinesisStreamExporter.java, src/main/java/ai/asserts/aws/exporter/RDSExporter.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/exporter/KinesisStreamExporterTest.java, src/test/java/ai/asserts/aws/exporter/RDSExporterTest.java, src/test/java/ai/asserts/aws/exporter/RedshiftExporterTest.java
RDS DB Clusters and Instances resource using direct API
[ch12326]
=> RDS cluster,instance support

build.gradle, src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/exporter/SNSTopicExporter.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/exporter/SNSTopicExporterTest.java
=> SNS Topics from direct API

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/exporter/LBToASGRelationBuilder.java, src/main/java/ai/asserts/aws/exporter/ResourceExporter.java, src/test/java/ai/asserts/aws/exporter/LBToASGRelationBuilderTest.java
=> Asg from direct api

src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/exporter/SQSQueueExporter.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java
=> Fix log messages and some other minor fixes

src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/exporter/KinesisAnalyticsExporter.java, src/main/java/ai/asserts/aws/exporter/KinesisFirehoseExporter.java, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
=> Add namespace in the resource metrics in a few places

agent-scrape-config.yml, config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java, src/main/java/ai/asserts/aws/exporter/LoadBalancerExporter.java
* Fix k8s lb tag name
* Change from HTTP SD to file based SD. Agent will need to become a sidecar container now
=> Fix k8s lb tag name

config/src/main/java/ai/asserts/aws/config/ECSTaskDefScrapeConfig.java, config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/ScrapeConfigProvider.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java, src/main/java/ai/asserts/aws/exporter/LBToECSRoutingBuilder.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
=> Few enhancements

config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/exporter/LoadBalancerExporter.java, src/main/java/ai/asserts/aws/exporter/ResourceExporter.java
* Tighten empty response check
=> Tighten empty response checks

src/main/java/ai/asserts/aws/HealthCheckController.java
=> Health check endpoint

src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/MetricNameUtil.java, src/main/java/ai/asserts/aws/RateLimiter.java, src/test/java/ai/asserts/aws/RateLimiterTest.java
=> Add error type to error count metric

src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java, src/main/java/ai/asserts/aws/resource/ResourceMapper.java, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java, src/test/java/ai/asserts/aws/exporter/ECSTaskUtilTest.java, src/test/java/ai/asserts/aws/resource/ResourceMapperTest.java
[ch12929]
* Workload to have either service name or task definition name
* Restore pod label prefixed with workload
=> Restore pod label

Dockerfile
=> Switch to Amazon Corretto base images

src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporter.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/test/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporterTest.java
=> Ec2 instance dnsname ip

src/main/java/ai/asserts/aws/exporter/RedshiftExporter.java, src/test/java/ai/asserts/aws/exporter/RedshiftExporterTest.java
=> Resource tags for Redshift

src/main/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporter.java, src/test/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporterTest.java
=> Remove Ec2Client.describeTags

Dockerfile
=> Update packages to latest

config/src/main/java/ai/asserts/aws/config/RelabelConfig.java, config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, config/src/test/java/ai/asserts/aws/config/RelabelConfigTest.java, config/src/test/java/ai/asserts/aws/config/ScrapeConfigTest.java, src/main/java/ai/asserts/aws/AccountProvider.java, src/main/java/ai/asserts/aws/exporter/BasicMetricCollector.java, src/main/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporter.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java, src/test/java/ai/asserts/aws/exporter/BasicMetricCollectorTest.java, src/test/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporterTest.java, src/test/java/ai/asserts/aws/exporter/ECSTaskUtilTest.java
=> Metric drop config support

config/src/main/java/ai/asserts/aws/config/AuthConfig.java, config/src/main/java/ai/asserts/aws/config/DimensionToLabel.java, config/src/main/java/ai/asserts/aws/config/ECSTaskDefScrapeConfig.java, config/src/main/java/ai/asserts/aws/config/LogScrapeConfig.java, config/src/main/java/ai/asserts/aws/config/MetricConfig.java, config/src/main/java/ai/asserts/aws/config/NamespaceConfig.java, config/src/main/java/ai/asserts/aws/config/RelabelConfig.java, config/src/main/java/ai/asserts/aws/config/TagExportConfig.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java
=> Set `@JsonIgnoreProperties(ignoreUnknown = true)` where missing

config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/test/java/ai/asserts/aws/RateLimiterTest.java, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
[ch13049]
* Cross VPC Scraping config
* Comment flaky rate limiter test
=> Cross VPC scraping config

src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java, src/test/java/ai/asserts/aws/exporter/ECSTaskUtilTest.java
=> Apply relabeling to ECS Target labels

config/src/main/java/ai/asserts/aws/config/RelabelConfig.java, config/src/test/java/ai/asserts/aws/config/RelabelConfigTest.java
=> Label inclusion filter fix

src/dist/conf/cloudwatch_scrape_config_sample.yml
=> Add comments in YAML config

config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/ScrapeConfigProvider.java, src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmFetcher.java, src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmMetricExporter.java, src/main/java/ai/asserts/aws/cloudwatch/alarms/AlertsProcessor.java, src/main/java/ai/asserts/aws/exporter/BasicMetricCollector.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/exporter/LambdaCapacityExporter.java, src/main/java/ai/asserts/aws/exporter/LambdaEventSourceExporter.java, src/main/java/ai/asserts/aws/exporter/LambdaInvokeConfigExporter.java, src/main/java/ai/asserts/aws/exporter/LambdaLogMetricScrapeTask.java, src/main/java/ai/asserts/aws/exporter/LoadBalancerExporter.java, src/main/java/ai/asserts/aws/exporter/MetricSampleBuilder.java, src/main/java/ai/asserts/aws/exporter/MetricScrapeTask.java, src/main/java/ai/asserts/aws/exporter/RDSExporter.java, src/main/java/ai/asserts/aws/exporter/ScrapeConfigExporter.java, src/test/java/ai/asserts/aws/exporter/MetricSampleBuilderTest.java
=> Improve Exception handling in all metric collector collect() methods

config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
=> Suppress ECS Target logging

config/src/main/java/ai/asserts/aws/config/MetricConfig.java, config/src/main/java/ai/asserts/aws/config/NamespaceConfig.java, config/src/main/java/ai/asserts/aws/config/PatternMatcher.java, config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, config/src/main/java/ai/asserts/aws/model/CWNamespace.java, config/src/test/java/ai/asserts/aws/config/MetricConfigTest.java, config/src/test/java/ai/asserts/aws/config/NamespaceConfigTest.java, config/src/test/java/ai/asserts/aws/config/PatternMatcherTest.java, src/main/java/ai/asserts/aws/ScrapeConfigProvider.java, src/main/java/ai/asserts/aws/resource/ResourceTagHelper.java
=> Support enhanced dimension filtering

src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmFetcher.java, src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmFetcherTest.java
=> Add more logs

src/main/java/ai/asserts/aws/exporter/ApiGatewayToLambdaBuilder.java, src/test/java/ai/asserts/aws/exporter/ApiGatewayToLambdaBuilderTest.java
=> Fix NPE in ApiGatewayToLambdaBuilder

src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java
=> Exclude Scrape Config retrieval from pause

src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java
=> Fetch config every minute

config/src/main/java/ai/asserts/aws/config/NamespaceConfig.java, config/src/main/java/ai/asserts/aws/config/RelabelConfig.java
=> Optimize relabel rule matching

src/main/java/ai/asserts/aws/exporter/MetricScrapeTask.java, src/test/java/ai/asserts/aws/exporter/MetricScrapeTaskTest.java
=> Not all S3 metrics are daily metrics

src/main/java/ai/asserts/aws/MetricNameUtil.java, src/test/java/ai/asserts/aws/MetricNameUtilTest.java
=> Fix snake case

Dockerfile
=> Update libraries for vulnerability fixes

config/src/main/java/ai/asserts/aws/model/CWNamespace.java
=> Fix Namespace for ElastiCache

config/src/main/java/ai/asserts/aws/config/DimensionToLabel.java, config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, config/src/test/java/ai/asserts/aws/config/ScrapeConfigTest.java, src/dist/conf/default_relabel_rules.yml, src/main/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamController.java, src/main/java/ai/asserts/aws/exporter/LabelBuilder.java, src/main/java/ai/asserts/aws/resource/ResourceConfigController.java, src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmMetricConverterTest.java, src/test/java/ai/asserts/aws/exporter/LabelBuilderTest.java, src/test/java/ai/asserts/aws/resource/ResourceConfigControllerTest.java
=> Don't add entity type label

build.gradle, config/src/main/java/ai/asserts/aws/model/CWNamespace.java, src/dist/conf/cloudwatch_scrape_config_sample.yml, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/exporter/EMRExporter.java, src/main/java/ai/asserts/aws/resource/ResourceType.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/exporter/EMRExporterTest.java
[ch14248]
```aws_resource{account_id="342994379019",asserts_env="dev",asserts_site="dev",aws_resource_type="AWS::ElasticMapReduce::Cluster",job="j-38XFS1BPO6IKN",job_flow_id="j-38XFS1BPO6IKN",name="emr-poc-hadoop-hive-hue-pig-tez",namespace="AWS/ElasticMapReduce",region="us-west-2",} 1.0```
=> Discover EMR Clusters

src/main/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporter.java, src/test/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporterTest.java
=> Discover running EC2 Instances

gradle.properties, src/main/java/ai/asserts/aws/AWSClientProvider.java, src/test/java/ai/asserts/aws/AWSClientProviderTest.java
=> Fix AWS ClientProvider Client Cache bug

config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/AccountProvider.java, src/test/java/ai/asserts/aws/AccountProviderTest.java
=> Don't fetch account configs by default

src/main/java/ai/asserts/aws/exporter/TargetGroupLBMapProvider.java, src/test/java/ai/asserts/aws/exporter/TargetGroupLBMapProviderTest.java
[ch14559]
```
aws_lb_to_ec2_instance{account_id="342994379019",asserts_env="dev",asserts_site="dev",ec2_instance_id="i-002ef23938bed48b3",lb_id="5951714dca12f0f6",lb_name="asserts-inc-jenkins-dev",port="8080",region="us-west-2",} 1.0
aws_lb_to_ec2_instance{account_id="342994379019",asserts_env="dev",asserts_site="dev",ec2_instance_id="i-013b643ba8a989441",lb_id="e67fb7d6d9786aab",lb_name="ride-service-lb",port="80",region="us-west-2",} 1.0
aws_lb_to_ec2_instance{account_id="342994379019",asserts_env="dev",asserts_site="dev",ec2_instance_id="i-013b643ba8a989441",lb_id="e67fb7d6d9786aab",lb_name="ride-service-lb",port="80",region="us-west-2",} 1.0
```
=> Emit metric for LB <-> EC2 Relationship

src/main/java/ai/asserts/aws/exporter/LoadBalancerExporter.java
[ch14559]
```
aws_lb_to_ec2_instance{account_id="342994379019",asserts_env="dev",asserts_site="dev",ec2_instance_id="i-09bffbc337acf1cdb",lb_name="ride-service-payment-classic-lb",lb_type="classic",port="80",region="us-west-2",} 1.0
aws_lb_to_ec2_instance{account_id="342994379019",asserts_env="dev",asserts_site="dev",ec2_instance_id="i-013b643ba8a989441",lb_name="ride-service-payment-classic-lb",lb_type="classic",port="80",region="us-west-2",} 1.0
```
=> ClassicLB to EC2 relationship metric

src/main/java/ai/asserts/aws/AWSClientProvider.java, src/main/java/ai/asserts/aws/ApiAuthenticator.java, src/main/java/ai/asserts/aws/resource/ResourceTagHelper.java
=> TTL after write instead of after read

Dockerfile, build.gradle, gradle.properties
=> Revert security fixes remove addl packages

src/main/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporter.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/lambda/LambdaFunctionScraper.java, src/test/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporterTest.java, src/test/java/ai/asserts/aws/lambda/LambdaFunctionScraperTest.java
=> Filter Lambda functions and EC2 instances by subnets

build.gradle, config/build.gradle, config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, config/src/test/java/ai/asserts/aws/config/ScrapeConfigTest.java
[ch15206]
* Explicitly set compilation source and target versions
* Switch to target scraping over HTTPS based on environment variable
=> Explicitly set compilation source and target versions

config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, config/src/test/java/ai/asserts/aws/config/ScrapeConfigTest.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
=> TLS only for customer tasks

Dockerfile.agent
=> Update exporter vmagent sidecar container

src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
=> Filter ECS Tasks by subnets

src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java
=> Fix ecs discovered targets log message

src/main/java/ai/asserts/aws/exporter/BasicMetricCollector.java
=> Expire inactive metrics

config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/MetricNameUtil.java, src/main/java/ai/asserts/aws/ScrapeConfigProvider.java, src/main/java/ai/asserts/aws/SnakeCaseUtil.java, src/main/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamController.java, src/test/java/ai/asserts/aws/MetricNameUtilTest.java, src/test/java/ai/asserts/aws/ScrapeConfigProviderTest.java, src/test/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamControllerTest.java
=> Exclude metrics that are not configured

Dockerfile, config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/MetricTaskManager.java, src/main/java/ai/asserts/aws/cloudwatch/query/MetricQueryProvider.java, src/test/java/ai/asserts/aws/MetricTaskManagerTest.java, src/test/java/ai/asserts/aws/cloudwatch/query/MetricQueryProviderTest.java
=> CW Metrics Pull on/off flag

src/main/java/ai/asserts/aws/MetricTaskManager.java, src/test/java/ai/asserts/aws/MetricTaskManagerTest.java
=> Alarm fetch only on primary exporter

config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java
=> Reorder fields in ScrapeConfig class

Dockerfile, src/main/java/ai/asserts/aws/BeanConfiguration.java, src/main/java/ai/asserts/aws/DeploymentModeUtil.java, src/main/java/ai/asserts/aws/account/HekateDistributedAccountProvider.java, src/main/java/ai/asserts/aws/account/SingleInstanceAccountProvider.java, src/test/java/ai/asserts/aws/DeploymentModeUtilTest.java, src/test/java/ai/asserts/aws/account/HekateDistributedAccountProviderTest.java
=> Create Account Provider through @Configuration instead of @Component

src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmFetcher.java, src/main/java/ai/asserts/aws/exporter/MetricScrapeTask.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmFetcherTest.java, src/test/java/ai/asserts/aws/exporter/MetricScrapeTaskTest.java
=> Tighten single-tenant mode checks

src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/exporter/ECSTaskProvider.java, src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java, src/main/java/ai/asserts/aws/exporter/Labels.java, src/test/java/ai/asserts/aws/exporter/ECSTaskProviderTest.java, src/test/java/ai/asserts/aws/exporter/ECSTaskUtilTest.java
=> Expose ECS Container Log Configuration as a metric

build.gradle, src/main/java/ai/asserts/aws/AwsExporterBeanConfiguration.java, src/main/java/ai/asserts/aws/EnvironmentConfig.java, src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/MetricTaskManager.java, src/main/java/ai/asserts/aws/SingleTenantScrapeConfigProvider.java, src/main/java/ai/asserts/aws/account/SingleInstanceAccountProvider.java, src/main/java/ai/asserts/aws/cloudwatch/query/MetricQueryProvider.java, src/main/java/ai/asserts/aws/exporter/AccountIDProvider.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/test/java/ai/asserts/aws/EnvironmentConfigTest.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/MetricTaskManagerTest.java, src/test/java/ai/asserts/aws/SingleTenantScrapeConfigProviderTest.java, src/test/java/ai/asserts/aws/account/SingleInstanceAccountProviderTest.java, src/test/java/ai/asserts/aws/cloudwatch/query/MetricQueryProviderTest.java, src/test/java/ai/asserts/aws/exporter/AccountIDProviderTest.java, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
=> Rename on/off flag

src/main/java/ai/asserts/aws/MetadataTaskManager.java, src/main/java/ai/asserts/aws/account/HekateDistributedAccountProvider.java, src/main/java/ai/asserts/aws/account/SingleInstanceAccountProvider.java, src/main/java/ai/asserts/aws/cluster/HekateCluster.java, src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java, src/main/java/ai/asserts/aws/exporter/ECSTaskProvider.java, src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java, src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java, src/test/java/ai/asserts/aws/account/HekateDistributedAccountProviderTest.java, src/test/java/ai/asserts/aws/cluster/HekateClusterTest.java, src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java, src/test/java/ai/asserts/aws/exporter/ECSTaskProviderTest.java, src/test/java/ai/asserts/aws/exporter/ECSTaskUtilTest.java
=> Fix NPEs in exporter SaaS mode

src/main/java/ai/asserts/aws/exporter/ECSTaskProvider.java, src/test/java/ai/asserts/aws/exporter/ECSTaskProviderTest.java
=> Fix in a few more places

src/main/java/ai/asserts/aws/exporter/TargetGroupLBMapProvider.java
=> Discover link between ALB and ECS Instances too

src/test/java/ai/asserts/aws/AWSApiCallRateLimiterTest.java
=> Remove flaky test for now

src/main/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamController.java, src/test/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamControllerTest.java
=> Add prefix `d_` for dimension labels

config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java, src/main/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporter.java, src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java, src/test/java/ai/asserts/aws/exporter/EC2ToEBSVolumeExporterTest.java, src/test/java/ai/asserts/aws/exporter/ECSTaskUtilTest.java
=> Flag to disable EC2 API usage

src/main/java/ai/asserts/aws/exporter/ScrapeConfigExporter.java, src/test/java/ai/asserts/aws/exporter/ScrapeConfigExporterTest.java
=> Fix NPE in ScrapeConfigExporter
