asserts/aws-cloudwatch-exporter

- Dockerfile
Story details: https://app.shortcut.com/asserts/story/10038
@jradhakrishnan this is the basic change need to bake vmagent into same image alongside `aws-cw-exporter`
I added it to container's `/bin` folder so it's easily usable like any other CLI util.
A couple open questions.
How should we invoke VMAgent?
From exporter Java code or container init script?
To verify it's working/available run:
```sh
docker build -t ai.asserts.aws-exporter:latest .
docker run ai.asserts.aws-exporter:latest "/bin/vmagent" -h
```
VMAgent can be launched with a flag that enables it to be configured via environment variables.
```yaml
-envflag.enable
Whether to enable reading flags from environment variables additionally to command line. 
Command line flag values have priority over values from environment vars. …
```
> Bake VMAgent into AWS-Exporter image

- chart/Chart.yaml
- chart/templates/_helpers.tpl
- chart/templates/deployment.yaml
- chart/templates/service.yaml
- chart/templates/serviceaccount.yaml
- chart/values.yaml
Story details: https://app.shortcut.com/asserts/story/10672
Already created new image repo in DockerHub
Here Im updating the image repo the chart pulls from and and 
adding a Service Account so AWS Cloudwatch Exporter can pull from DockerHub
> Migrate AWS Cloudwatch Exporter use dockerhub instead of ECR

- src/main/java/ai/asserts/aws/exporter/ResourceExporter.java
- src/main/java/ai/asserts/aws/resource/Resource.java
- src/main/java/ai/asserts/aws/resource/ResourceMapper.java
- src/main/java/ai/asserts/aws/resource/ResourceType.java
- src/test/java/ai/asserts/aws/exporter/ResourceExporterTest.java
- src/test/java/ai/asserts/aws/resource/ResourceMapperTest.java
[ch10841]
Some discovered resource ids tend to be the ARNs or in case of SQS Queue the Queue URL. To shorten entity names, we can get the resource name from the ARN.
> ARN parsing support for more ARNs

- src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmController.java
Adding Rest End Point to test the ingress for aws-exporter for alarms.
[ch10882]
> Add support for events and alarms from cloud trail

- src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmMetricExporter.java
- src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmMetricExporterTest.java
change aws_cloudwatch_alarm metric value to 1. Record at the timestamp at which alarm fired if it is with in 30 second of current time, else record timestamp as now -30 seconds and generate histogram with difference value.
[ch10882]
> change metric value and timestamp

- src/dist/conf/cloudwatch_scrape_config_sample.yml
- src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfig.java
- src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigProvider.java
- src/main/java/ai/asserts/aws/cloudwatch/config/TagExportConfig.java
- src/main/java/ai/asserts/aws/exporter/LambdaCapacityExporter.java
- src/main/java/ai/asserts/aws/exporter/LambdaEventSourceExporter.java
- src/main/java/ai/asserts/aws/exporter/LambdaInvokeConfigExporter.java
- src/main/java/ai/asserts/aws/lambda/LambdaFunction.java
- src/main/java/ai/asserts/aws/lambda/LambdaFunctionBuilder.java
- src/main/java/ai/asserts/aws/lambda/LogEventMetricEmitter.java
- src/main/java/ai/asserts/aws/resource/TagFilterResourceProvider.java
- src/test/java/ai/asserts/aws/cloudwatch/config/TagExportConfigTest.java
- src/test/java/ai/asserts/aws/exporter/LambdaCapacityExporterTest.java
- src/test/java/ai/asserts/aws/exporter/LambdaEventSourceExporterTest.java
- src/test/java/ai/asserts/aws/exporter/LambdaInvokeConfigExporterTest.java
- src/test/java/ai/asserts/aws/lambda/LambdaFunctionBuilderTest.java
- src/test/java/ai/asserts/aws/lambda/LogEventEmitterTest.java
- src/test/java/ai/asserts/aws/resource/TagFilterResourceProviderTest.java
[ch11037]
Add `account` in all emitted metrics
Add support for include/exclude which tags to export
> Add `account` in all emitted metrics

- src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmMetricConverter.java
Adding metric_namespace label to keep origin namespace when alarm state change notification is pushed to aws_exporter.
> add metric_namespace label when state change

- src/main/java/ai/asserts/aws/exporter/KinesisFirehoseExporter.java
For Kinesis firehose resource job label mapping was missing which used in entities mapping. Adding it to be used for entity mapping.
[ch11455]
> Adding job label

- src/main/java/ai/asserts/aws/exporter/ResourceExporter.java
- src/test/java/ai/asserts/aws/exporter/ResourceExporterTest.java
When resources are empty buildfamily method in metric builder was failing with Index Out of bound exception, fixing it.
[ch11561]
> IndexOutofBoundException when resource is empty

- src/main/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigProvider.java
- src/test/java/ai/asserts/aws/cloudwatch/config/ScrapeConfigProviderTest.java
- src/test/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamProcessorTest.java
When assert host, user and secret key is defined, read scrape config from api-server end point else continue the usual flow.
[ch11574]
> Read scrape config from api-server

- src/main/java/ai/asserts/aws/MetricNameUtil.java
- src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmMetricExporter.java
- src/main/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamController.java
- src/main/java/ai/asserts/aws/resource/ResourceConfigController.java
- src/main/java/ai/asserts/aws/resource/ResourceType.java
- src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmMetricExporterTest.java
- src/test/java/ai/asserts/aws/cloudwatch/metrics/MetricStreamControllerTest.java
- src/test/java/ai/asserts/aws/resource/ResourceConfigControllerTest.java
For configured resources in aws exporter if there is any change in configuration it will be pushed to aws exporter through Kinesis stream.
Process these events and convert to metric if the resource type is in the list of resource types configured and change type is not create. We discovered new resources create using a different path.
[ch11385]
> Process Resource Config change

- config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java
- config/src/test/java/ai/asserts/aws/config/ScrapeConfigTest.java
- src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java
- src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java
- src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
- src/test/java/ai/asserts/aws/exporter/ECSTaskUtilTest.java
[ch11970]
Tetra science has lots of ECS tasks. Having to configure the metric path for each will be painful.
- If Prometheus export path and port are specified using Docker labels use that
- Scrape all ECS Tasks by default assuming the metric path is `/metrics`.
- Allow for scraping only configured container/ports
> Scrape all ECS tasks by default

- config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java
- src/dist/conf/cloudwatch_scrape_config_sample.yml
- src/main/java/ai/asserts/aws/MetricTaskManager.java
- src/main/java/ai/asserts/aws/cloudwatch/alarms/AlarmFetcher.java
- src/test/java/ai/asserts/aws/MetricTaskManagerTest.java
- src/test/java/ai/asserts/aws/cloudwatch/alarms/AlarmFetcherTest.java
While pulling the cloud watch alarm for the AWS account, we can publish the metric directly compared to the flow where we get a callback from the cloud watch alarm state change notification.
In this flow of pulling the cloud watch alarm convert it to metric and publish directly.
Since we are pulling alarms we will be doing this by default every 1 min.
[ch12437]
> Exporter is emitting stale CW Alarm

- Dockerfile.agent
[ch12992]
Use custom docker image of vmagent with amazonlinux as base image. The image was build from source v1.80.0 as follows
* `PKG_TAG=1.80.1 ROOT_IMAGE=amazonlinux:2.0.20220719.0 make package-vmagent`
* `docker tag victoriametrics/vmagent:1.80.1 asserts/vmagent:v1.80.1`
Tested with this in chief and everything seems to be working fine.
> vmagent security fix

- config/src/main/java/ai/asserts/aws/config/NamespaceConfig.java
- src/dist/conf/default_relabel_rules.yml
- src/main/java/ai/asserts/aws/MetricTaskManager.java
- src/main/java/ai/asserts/aws/cloudwatch/query/MetricQueryProvider.java
- src/main/java/ai/asserts/aws/exporter/LBToLambdaRoutingBuilder.java
- src/main/java/ai/asserts/aws/exporter/TargetGroupLBMapProvider.java
- src/test/java/ai/asserts/aws/cloudwatch/query/MetricQueryProviderTest.java
- src/test/java/ai/asserts/aws/exporter/LBToLambdaRoutingBuilderTest.java
- src/test/java/ai/asserts/aws/exporter/TargetGroupLBMapProviderTest.java
[ch13398]
* Fix for TargetGroupNotFoundException errors
* Add `enabled` flag for Metric Namespace configs to enable seeded-but-disabled metric configurations
> Fix for TargetGroupNotFoundException errors

- src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java
- src/test/java/ai/asserts/aws/exporter/ECSTaskUtilTest.java
[ch13709]
Switch to host port for target discovery. This should work for all [network modes](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-networking.html).
> Switch to host port for target discovery.

- config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java
- src/main/java/ai/asserts/aws/AWSClientProvider.java
- src/main/java/ai/asserts/aws/AccountProvider.java
- src/main/java/ai/asserts/aws/ApiServerConstants.java
- src/main/java/ai/asserts/aws/MetadataTaskManager.java
- src/main/java/ai/asserts/aws/MetricTaskManager.java
- src/main/java/ai/asserts/aws/ScrapeConfigProvider.java
- src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java
- src/test/java/ai/asserts/aws/AccountProviderTest.java
- src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java
- src/test/java/ai/asserts/aws/MetricTaskManagerTest.java
- src/test/java/ai/asserts/aws/ScrapeConfigProviderTest.java
- src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
[ch14527]
* Retrieve AWS Account configuration from API Server. Use AssumeRole/ExternalId if available
* Optionally, scrape the current account on which the exporter is running
* Pause accounts for which pause is requested.
> Retrieve AWS Account configuration from API Server

- src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java
- src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java
- src/main/java/ai/asserts/aws/exporter/Labels.java
- src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
- src/test/java/ai/asserts/aws/exporter/ECSTaskUtilTest.java
[ch14584]
```
aws_ecs_task_info{account_id="342994379019",asserts_env="dev",asserts_site="dev",cluster="asserts-aws-integration",region="us-west-2",service="exporter",task_id="daacc6fa3ffb4912aa737b23e40dc0dc",taskdef_family="asserts-aws-integration",taskdef_version="5",} 1.0
aws_ecs_task_info{account_id="342994379019",asserts_env="dev",asserts_site="dev",cluster="workload-generator",region="us-west-2",service="load-generator",task_id="01adfe39cd144d3fb68d9e4bb7e7b8f8",taskdef_family="workload-generator",taskdef_version="4",} 1.0
```
> Emit ECS Task Meta metric

- src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java
- src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java
- src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
- src/test/java/ai/asserts/aws/exporter/ECSTaskUtilTest.java
[ch15100]
The `INSTALL_ENV_NAME` and `SCRAPE_ECS_SUBNETS` will be set by the installer. See https://github.com/asserts/downloads/pull/32
> Support Multiple AWS Exporters in same AWS Account Region

- gradle.properties
- src/main/java/ai/asserts/aws/MetadataTaskManager.java
- src/main/java/ai/asserts/aws/MetricTaskManager.java
- src/main/java/ai/asserts/aws/RateLimiter.java
- src/main/java/ai/asserts/aws/cloudwatch/query/MetricQueryProvider.java
- src/main/java/ai/asserts/aws/exporter/ApiGatewayToLambdaBuilder.java
- src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java
- src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java
- src/main/java/ai/asserts/aws/exporter/MetricScrapeTask.java
- src/main/java/ai/asserts/aws/lambda/LambdaFunctionScraper.java
- src/main/java/ai/asserts/aws/resource/ResourceTagHelper.java
- src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java
- src/test/java/ai/asserts/aws/MetricTaskManagerTest.java
[ch15126]
```
INFO  2023-03-14 17:13:12.524 pool-1-thread-6 RateLimiter AWS API Call Counts {EcsClient/describeServices=2, EcsClient/describeTaskDefinition=1, EcsClient/describeTasks=1, EcsClient/listClusters=1, EcsClient/listServices=2, ResourceGroupsTaggingApiClient/getResources=2, listTasks=4}
```
> Add diagnostic logs for AWS rate limit error

- src/main/java/ai/asserts/aws/MetadataTaskManager.java
- src/main/java/ai/asserts/aws/exporter/ECSClusterProvider.java
- src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryController.java
- src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java
- src/main/java/ai/asserts/aws/exporter/ECSTaskProvider.java
- src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java
- src/main/java/ai/asserts/aws/exporter/LBToECSRoutingBuilder.java
- src/main/java/ai/asserts/aws/exporter/Paginator.java
- src/main/java/ai/asserts/aws/exporter/ResourceRelationExporter.java
- src/main/java/ai/asserts/aws/exporter/TargetGroupLBMapProvider.java
- src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java
- src/test/java/ai/asserts/aws/exporter/ECSClusterProviderTest.java
- src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryControllerTest.java
- src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
- src/test/java/ai/asserts/aws/exporter/ECSTaskProviderTest.java
- src/test/java/ai/asserts/aws/exporter/ECSTaskUtilTest.java
- src/test/java/ai/asserts/aws/exporter/LBToECSRoutingBuilderTest.java
- src/test/java/ai/asserts/aws/exporter/PaginatorTest.java
- src/test/java/ai/asserts/aws/exporter/ResourceRelationExporterTest.java
[ch15126]
* Separate class for discovering clusters.
* Exclude inactive clusters
* Cache clusters for 15 minutes
* Separate class for discovering tasks. Discover tasks in cluster directly.
* Cache Task Definition Lookups
* Reduce service discovery frequency to 15 minutes
* List Services only in LB to ECS Relationship building
> Refactor ECS Service Discovery

- Dockerfile.agent
- agent-scrape-config-https.yml
- agent-scrape-config.yml
- docker-compose.yaml
- env_agent.properties
- start-vmagent.sh
[ch15960]
The default had the file sd config for https which resulted in spurious errors. Depending on environment property switch between http or https scrape configs
Tested in chief with `SCRAPE_OVER_TLS` set to  both `true` and `false`. Works as expected
> Separate config for http and https

- .github/workflows/main-workflow.yaml
> Publish exporter jar to maven repo

- Dockerfile
- src/main/java/ai/asserts/aws/AwsExporterBeanConfiguration.java
- src/main/java/ai/asserts/aws/cluster/HekateCluster.java
[ch16008]
In the enterprise server mode, the `RestTemplate` is already created leading to a conflict. While, this can be resolved by `spring.main.allow-bean-definition-overriding=true`, this is not a solution. So create this only for the ECS mode of deployment
> Instantiate `RestTemplate` only when required

- src/main/java/ai/asserts/aws/MetadataTaskManager.java
- src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java
- src/main/java/ai/asserts/aws/exporter/ECSTaskProvider.java
- src/main/java/ai/asserts/aws/exporter/Labels.java
- src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java
- src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
- src/test/java/ai/asserts/aws/exporter/ECSTaskProviderTest.java
[ch16021]
* Fix File SD parse error by ignoring `logConfigs` part of `StaticConfig`
* ECS Scrape target generation is supported only in single-tenant i.e. ECS mode
* Make `Labels` a `SortedMap` to see labels in order
* Discover ECS scrape targets in async
> Fix file SD parse error

- src/main/java/ai/asserts/aws/MetadataTaskManager.java
- src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java
- src/test/java/ai/asserts/aws/MetadataTaskManagerTest.java
[ch15667]
* Always Emit ECS meta metrics. 
* Scrape target yaml generation only in single tenant mode
> Fix ECS Service Discovery

- config/src/main/java/ai/asserts/aws/config/ScrapeConfig.java
- src/main/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporter.java
- src/main/java/ai/asserts/aws/exporter/ECSTaskUtil.java
- src/test/java/ai/asserts/aws/exporter/ECSServiceDiscoveryExporterTest.java
- src/test/java/ai/asserts/aws/exporter/ECSTaskUtilTest.java
[ch16154]
* Build `StaticConfig` even when no prometheus targets
* Always emit meta metrics
* Build scrape target only when Prometheus instrumentation is present
* Remove unused config fields
* Reorder methods in `ECSTaskUtil` based on access
* Account level env name if present, precedes install level env name
> Emit ECS Meta metrics even when no prometheus instrumentation
